language: python
sudo: false

python:
  - "2.7"
  - "3.4"

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi

install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes ipython pyzmq numpy scipy nose matplotlib pandas Cython patsy statsmodels flake8 scikit-learn seaborn runipy pytables networkx
  - curl https://codeload.github.com/quantopian/zipline/legacy.zip/b89fc0c02871837900d79933040a53869a456ec4 > zipline.zip; unzip zipline; pushd quantopian-zipline-b89fc0c; python setup.py build_ext --inplace; python setup.py develop; popd
  - pip install nose_parameterized contextlib2 logbook
  - pip install git+https://github.com/Theano/Theano.git
  - pip install git+https://github.com/pymc-devs/pymc3.git
  - python setup.py build_ext --inplace

before_script:
  - "flake8 pyfolio"

script:
  - nosetests $TESTCMD
