site_name: pyfolio
repo_url: https://github.com/quantopian/pyfolio
site_author: Quantopian Inc.

pages:
- Overview: 'index.md'
- Releases: 'whatsnew.md'
- Tutorial:
  - 'Single stock': 'notebooks/single_stock_example.md'
  - 'Zipline algorithm': 'notebooks/zipline_algo_example.md'
  - 'Sector analysis': 'notebooks/sector_mappings_example.md'
  - 'Round trip analysis': 'notebooks/round_trip_tear_sheet_example.md'
  - 'Slippage analysis': 'notebooks/slippage_example.md'

extra_css: [extra.css]
